language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

# either whitelist or blacklist branches
# branches:
#     only:
#         - master
#     except:
#         - experimental

before_install:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi

install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install wget git g++ cmake libqt4-dev libqt4-opengl-dev python-docutils; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install git qt4; fi

before_script:
    # Build external tools
    - mkdir build_external
    - cd build_external
    - cmake ../thirdparty/external
    - make -j4
    - cd ..

script:
    # Build displaz
    - mkdir build
    - cd build
    - cmake ..
    - make -j4
    - cd ..

matrix:
    exclude:
        # Only check gcc on linux and clang on OS X
        - os: linux
          compiler: clang
        - os: osx
          compiler: gcc
    allow_failures:
        # For now ignore every OS X build issues
        - os: osx
