# Windows CI build via the Appveyor service

# branches to build
branches:
  except:
    - gh-pages

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# Build matrix variables -
#   * environment
#   * platform
#   * configuration
environment:
  matrix:
    - COMPILER: "Visual Studio 12 Win64"
    #- COMPILER: "Visual Studio 13 Win64"

# build platform, i.e. x86, x64, Any CPU.
platform:
  - x64

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build_script:
  - echo COMPILER = %COMPILER%, CONFIGURATION = %CONFIGURATION%
  - cmake -h
  - echo "Build third party dependencies"
  - mkdir build_external
  - cd build_external
  - cmake -G "Visual Studio 12 Win64" -D CMAKE_BUILD_TYPE={configuration} ..\thirdparty\external
  - cmake --build . --config %CONFIGURATION%
  - cd ..
  - echo "Build displaz"
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 12 Win64" -D CMAKE_PREFIX_PATH=C:\Qt\5.5\msvc2013_64 ..
  - cmake --build . --config %CONFIGURATION%

# TODO: Packaging
#  - cmake --build . --target package

test_script:
  - ctest

deploy: off
# TODO: deploy to S3 or GitHub Releases ?


notifications:
  # Email
  - provider: Email
    to: chris42f@gmail.com
    on_build_status_changed: true
